# Generated by Django 5.1.5 on 2025-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
