# Generated by Django 5.1.5 on 2025-06-02 00:12

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=portfolio_app.models.upload_to, verbose_name='Image'),
        ),
    ]
