# Generated by Django 5.1.5 on 2025-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('Blender', '3D Art'), ('KIVY', 'Andriod App'), ('WEB', 'Web development')], max_length=7),
        ),
    ]
