# Generated by Django 5.1.5 on 2025-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('ML', 'Machine Learning'), ('3D', 'blender'), ('WEB', 'Web development'), ('APP', 'andriod app')], default='Web Development', max_length=10)),
                ('project_details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
