# Generated by Django 5.1.5 on 2025-06-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='ContactRequest',
        ),
    ]
