# Generated by Django 5.1.5 on 2025-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactme_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
